Update minimum supported version to 2018.4
Unity-Technologies/com.autodesk.fbx pull request #310
Opened 2020-10-05 17:01 UTC by vkovec

2020-10-05 17:03 UTC, benoithudson approved these changes

2020-10-05 18:10 UTC, benoithudson requested changes

2020-10-05 18:10 UTC, benoithudson commented on build.py
>          cmake_exe = 'cmake3'
Can you remove the linux distro test and parse `cmake --version`? Or check if cmake3 exists and if not default to just cmake?

2020-10-05 18:23 UTC, benoithudson commented
And to use pip on yamato you need to set an environment variable so it can find the repository, see the python package. It got disconnected from the global pypi repository because of a security issue.

2020-10-05 20:08 UTC, benoithudson commented on build.py
> +    if cmake_version.startswith(b'cmake3'):
on my mac it's `cmake version 3.14.0`

2020-10-05 20:09 UTC, benoithudson commented on build.py
> +    if cmake_version.startswith(b'cmake3'):
but maybe I misunderstood this line's logic

2020-10-05 20:22 UTC, vkovec commented on build.py
> +    if cmake_version.startswith(b'cmake3'):
yes this should work no?

I'm checking if the result is `cmake3 version ...` vs `cmake ...`

2020-10-05 20:22 UTC, vkovec commented on build.py
> +    if cmake_version.startswith(b'cmake3'):
or maybe I should just parse the first part instead of checking if it starts with it

2020-10-06 16:56 UTC, benoithudson commented on build.py
> +    if cmake_version.startswith(b'cmake3'):
I don't understand this code.

If cmake is returning "cmake3 version 3.x.y" then why do you need to switch to cmake3 -- you're already using it.

If it's returning "cmake version 2.x.y" then you accept it even though it won't work.

I suspect the problem this code is trying to deal with just doesn't exist anymore so you could simply use cmake and go on with life.

2020-10-06 20:45 UTC, merged