Add Windows ARM64 support
Unity-Technologies/com.autodesk.fbx pull request #411
Opened 2024-03-06 14:09 UTC by thomas-tu

2024-03-06 14:09 UTC, unity-cla-assistant commented
[![CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/pull/badge/not_signed)](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.autodesk.fbx?pullRequest=411) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.autodesk.fbx?pullRequest=411) before we can accept your contribution.<br/><hr/>**Benoit Hudson** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.autodesk.fbx?pullRequest=411) it.</sub>

2024-03-13 22:06 UTC, benoithudson requested changes
We shouldn't include `proto.com.autodesk.fbx/Editor/Plugins/WinARM64/UnityFbxSdkNative.dll` in the commits.

2024-03-13 22:13 UTC, benoithudson commented on .yamato/upload-fbxsdk-to-stevedore.yml
> +#    e) linux: On linux, user needs to speficy where to install FBX SDK, for example at "/usr/FBX202034_FBXFILESDK_LINUX"
*specify

2024-03-14 14:28 UTC, mfe commented on .yamato/upload-fbxsdk-to-stevedore.yml
> +#    e) linux: On linux, user needs to speficy where to install FBX SDK, for example at "/usr/FBX202034_FBXFILESDK_LINUX"
Fixed in ecbb0e31eb3bf033d9082ebdb8171fd834f029af

2024-03-14 14:31 UTC, mfe approved these changes
LGTM for now (binary will be properly pushed and pulled in a later version). 
Tested manually on WinAR64, CI is green, APV green too.

2024-03-15 09:04 UTC, merged